sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sachetwasti61/docker-react -f Dockerfile.dev .
#  - docker run -e CI=true USERNAME/docker-react npm run test

script:
  - docker run -e CI=true sachetwasti61/docker-react npm run test